version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/user_management
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'